name: Run Tests

on:
  push:
    branches:
      - staging

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  

      - name: Install Pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Run tests
        env:
          API_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY= }}  # Use your secret here
        run: |
          pipenv run python manage.py test  # Replace with your tests execution command
          # You can access the secret using the environment variable API_KEY
